apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "postgres"
  DB_NAME: "postgres"
  DB_HOST: "co-working-space-analytics-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
metadata:
  name: db-env