apiVersion: v1
kind: Service
metadata:
  name: co-working-space-analytics
spec:
  selector:
    app.kubernetes.io/name: co-working-space-analytics
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: co-working-space-analytics
  labels:
    name: co-working-space-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      service: co-working-space-analytics
  template:
    metadata:
      labels:
        service: co-working-space-analytics
    spec:
      containers:
      - name: co-working-space-analytics
        image: 761503551478.dkr.ecr.us-east-1.amazonaws.com/project-3:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      restartPolicy: Always